name: Keep Alive

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  keep_alive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install project dependencies
        run: npm ci

      - name: Send Keep Alive Request
        run: curl -s https://date-form-prod.onrender.com/api/v1/home
